spring:
  application:
    name: md
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:local
    username: sa
    password:
  jpa:
    defer-datasource-initialization: true
  sql:
    init:
      mode: never
      encoding: utf-8

management:
  endpoints:
    web:
      exposure:
        include: "*"
