spring:
  application:
    name: md
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:local
    username: sa
    password:
  data:
    redis:
      host: k10a707.p.ssafy.io
      port: 6379
      timeout: 6
  jpa:
    defer-datasource-initialization: true
  sql:
    init:
      mode: never
      encoding: utf-8

management:
  endpoints:
    web:
      exposure:
        include: "*"
